# Database URL, Username, and Password
spring.datasource.url=jdbc:mysql://localhost:3306/my_petcare_db
spring.datasource.username=root
spring.datasource.password=Binushi@2000

# JPA / Hibernate Properties
#  after you created the Java Classes according to Tables this create automatically
spring.jpa.hibernate.ddl-auto=update

# to show SQL Queries in the Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver